#!/usr/bin/env ruby

require File.join(ENV["GISHTANK_GISH_DIR"], "lib", "gish.rb")

begin
  gish = Gish::Task.new arguments: ARGV
  gish.run!
rescue Interrupt
  puts gish.red(message: "\nExiting...")
  exit
end
